AWSTemplateFormatVersion: '2010-09-09'
Description: 'CICD: This cloudformation template download the code from github webhook and put it into an S3 bucket.'
Parameters:
  GithubToken:
    Description: GitHub API Token used for Status creation.
    Type: String
    Default: ""
    NoEcho : true
  ProjectName:
    AllowedPattern: "^[a-zA-Z0-9-_]*$"
    Description: Name to give the CodeBuild Project.
    MaxLength: '255'
    MinLength: '2'
    Type: String
    Default: "testwebhook"
  RepositoryUrl:
    Description: 'HTTPS Clone URL of the repository in GitHub. Example: ''https://github.com/<ORG>/repo.git'''
    Type: String
    Default: 
  PipelineartifactsBucketName:
    Type: String
    Description: Bucket name for the codepipeline source
    Default: "tests323062022"
  ArtifactFile:
    Description: Name of the Artifact File uploaded to S3
    Type: String
    Default: githubwebhook.zip
Resources:
  CodeBuildSourceCredential:
   Type: AWS::CodeBuild::SourceCredential
   Properties:
     AuthType: PERSONAL_ACCESS_TOKEN
     ServerType: GITHUB
     Token: !Ref GithubToken
  
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DescribeSubnets'
                - 'ec2:DescribeSecurityGroups'
                - 'ec2:DescribeDhcpOptions'
                - 'ec2:DescribeVpcs'
                - 'ec2:CreateNetworkInterfacePermission'
                Effect: Allow
                Resource: '*'
              - Action:
                - codebuild:*
                - codecommit:GetBranch
                - codecommit:GetCommit
                - codecommit:GetRepository
                - codecommit:ListBranches
                - codecommit:ListRepositories
                - cloudwatch:GetMetricStatistics
                - ec2:DescribeVpcs
                - ec2:DescribeSecurityGroups
                - ec2:DescribeSubnets
                - ecr:DescribeRepositories
                - ecr:ListImages
                - elasticfilesystem:DescribeFileSystems
                - events:DeleteRule
                - events:DescribeRule
                - events:DisableRule
                - events:EnableRule
                - events:ListTargetsByRule
                - events:ListRuleNamesByTarget
                - events:PutRule
                - events:PutTargets
                - events:RemoveTargets
                - logs:GetLogEvents
                - s3:GetBucketLocation
                - s3:ListAllMyBuckets
                - s3:PutObject
                Effect: Allow
                Resource: "*"
              - Action:  
                - logs:DeleteLogGroup
                Effect: Allow
                Resource: arn:aws:logs:*:*:log-group:/aws/codebuild/*:log-stream:*
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                Resource: arn:aws:ssm:*:*:parameter/CodeBuild/*
              - Effect: Allow
                Action:
                  - ssm:StartSession
                Resource: arn:aws:ecs:*:*:task/*/*
              - Sid: CodeStarConnectionsReadWriteAccess
                Effect: Allow
                Action:
                  - codestar-connections:CreateConnection
                  - codestar-connections:DeleteConnection
                  - codestar-connections:UpdateConnectionInstallation
                  - codestar-connections:TagResource
                  - codestar-connections:UntagResource
                  - codestar-connections:ListConnections
                  - codestar-connections:ListInstallationTargets
                  - codestar-connections:ListTagsForResource
                  - codestar-connections:GetConnection
                  - codestar-connections:GetIndividualAccessToken
                  - codestar-connections:GetInstallationUrl
                  - codestar-connections:PassConnection
                  - codestar-connections:StartOAuthHandshake
                  - codestar-connections:UseConnection
                Resource: arn:aws:codestar-connections:*:*:connection/*
              - Sid: CodeStarNotificationsReadWriteAccess
                Effect: Allow
                Action:
                  - codestar-notifications:CreateNotificationRule
                  - codestar-notifications:DescribeNotificationRule
                  - codestar-notifications:UpdateNotificationRule
                  - codestar-notifications:DeleteNotificationRule
                  - codestar-notifications:Subscribe
                  - codestar-notifications:Unsubscribe
                Resource: "*"
                Condition:
                  StringLike:
                    codestar-notifications:NotificationsForResource: arn:aws:codebuild:*
              - Sid: CodeStarNotificationsListAccess
                Effect: Allow
                Action:
                  - codestar-notifications:ListNotificationRules
                  - codestar-notifications:ListEventTypes
                  - codestar-notifications:ListTargets
                  - codestar-notifications:ListTagsforResource
                Resource: "*"
              - Sid: CodeStarNotificationsSNSTopicCreateAccess
                Effect: Allow
                Action:
                  - sns:CreateTopic
                  - sns:SetTopicAttributes
                Resource: arn:aws:sns:*:*:codestar-notifications*
              - Sid: SNSTopicListAccess
                Effect: Allow
                Action:
                  - sns:ListTopics
                  - sns:GetTopicAttributes
                Resource: "*"
              - Sid: CodeStarNotificationsChatbotAccess
                Effect: Allow
                Action:
                  - chatbot:DescribeSlackChannelConfigurations
                Resource: "*"
  GithubCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Ref: ProjectName
      Artifacts:
        Name: !Sub "${ArtifactFile}"
        Type: S3
        Location:
          Ref: PipelineartifactsBucketName
        Packaging: ZIP
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
      Source:
        Auth:
          Type: OAUTH
          Resource: !Ref CodeBuildSourceCredential
        Type: GITHUB
        Location: !Ref RepositoryUrl
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - echo Uploading Artifacts to S3
          artifacts:
            files:
              - '**/*'
      Triggers:
        Webhook: false 
  CreateWebhook:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub CreateWebhook-${ProjectName}
      Description: Webhook to trigger builds
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
        EnvironmentVariables:
          - Value: !Ref GithubCodeBuildProject
            Name: 'PrjName'
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          env:
            shell: bash
          phases:
              install:
                  commands:
                      - aws --version
              build:
                  commands:
                    - > 
                      aws codebuild create-webhook --project-name $PrjName \
      TimeoutInMinutes: 10
Outputs:
  CodeBuildProject:
    Description: CodeBuild Project triggered by GitHub
    Value: !Ref GithubCodeBuildProject
    
    